# Generated by Django 4.2.7 on 2023-12-02 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial')
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sentences',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
    ]
